{% set version = "1.3-21" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-regress
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/regress_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/regress/regress_{{ version }}.tar.gz
  sha256: 7fbd2d9d4759ef90c7582c4037814c014180c1326fb0ba9b8b0964f07c0b6e56
  
build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('regress')"           # [not win]
    - "\"%R%\" -e \"library('regress')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/regress/index.html
  license: GPL-2.0-or-later
  summary: Functions to fit Gaussian linear model by maximising the residual log likelihood where the covariance structure can be written as a linear combination of known matrices.  Can be used for multivariate models and random effects models.  Easy straight forward manner to specify random effects models, including random
    interactions. Code now optimised to use Sherman Morrison Woodbury identities for matrix inversion in random effects models. We've added the ability to fit models using any kernel as well as a function to return the mean and covariance of random effects conditional on the data (BLUPs).
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
