travis:
  secure:
    BINSTAR_TOKEN: bpAgkalJU4dJFlq91+mhMPvd/FL7dw6YsIvPsuUwfYgR6e8AmN6JDHoo5sWv2DbY1zD0MaHjL6XxYrkPUr0A4+SijeKMve8+QJOKPWGpbuG4gsY6tlC/N0Fjgf0SNd1NpS03UkQjzkADLqxYGJprjQAn46Rhfio3u2LzNsRG1HQUDZOhH9SINMK1fc2pBVO5fBrE8RvUTm375BJdAa/+dFAPZFkslX6KMLZn87gijdUzqGC0WQwJCGcrcRbG1Ur8RYrcNntD26pzQje7IP6QRsN23nl1ZBgQSbXZp7C2CdRaY0s6Hm/REzUbeMKxZlSKsxBt0je2ymf0Jny5aDm4BzDUAzxU2L6qZ/02M4UyYrtu+a0WOoZY/WWjkJigyBKZSVbvi5o/OnOhysfdugHBjt0fAcvDALYul9q7fSVBWCMVr5Sa8fRpwa1fKzbmfv2Ox4GA48zHK7V71CBqCGd6sDLcBjmgmvKPgAvRta7vLs3ufG3EmTCEpgE1qPEM8YPaRzy2lRx2KyW3gar8KADx6i+DieoDJiO/S0saw7DHy0yS7a8EXxPyQP168n77U8mS4jLwdz0heI0i4EuWk+DtN87dPwK6kXTGYIEsteg6E321LeJSn9HGmW7E4T3ne0DjshxCXbY6mSoE3tJ6ASRwKttMYMtF97f+cCl0KpM9MiM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
