travis:
  secure:
    BINSTAR_TOKEN: odbuk5JzIZBTmzBBviwk+FfKNtu9H9FaqV3dzZamxGR5zW3OMuQ1GHss3HdirB+PMNKo7pQjA8p1Yko+VHDT8u+55hGMQoBdaAThvihjcyOPt1GUIKM/fa3YGQ27v8UwPP7OL4RGot139cwmvGHBUTF0YhrxsYWlCMxJjeGG0CE6Xtt0XHLnwaktL30Lfr7NtvCW/97ZwqW7shcB9+2U6hqKFJ1D+lS5k8f8le2J8SViNj3qzvZ/bDTuK8luo/Xez6xDmlqyA42l52ZrqWWlru5RLOdfYRdBTuwIQZRTSx0KGGmnS+CZy3CpHylgNnHDXq90knRQV10NHNxcFtQLeKWv2T2EYXB1C/WJwN4p2ukItxowrpTNUrxtVmWVMuqC0N79Li6UmkV/BdO/6dg5B11P9mbqICMtqkN3w+xxYgIB8djDlnS0oPAux+q9TMnFh05fJonHCnsBQUlyX5fZEw2LQT7KK9b2a98iesH6NtmpB9B/MSIKb+OsnjcY5232bRuaXD3UejSodJkBDK6qHaDOFD1SVZv0MKpLz56EbbhlEmJbYG625LidlVM/LKWphC7c0qIVtJBrFzqgJcf880lgUfmqCH1ps2SKhc5pWfK5peYY+zF+Os91WH7I6AhSeMoXVON5UU+L+bwsQpIRUwT0nJlsuNY+78/005Mks4k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
