travis:
  secure:
    BINSTAR_TOKEN: RPYHP7eJh2P0wmCGOjTVwpaHt3yBBXACl1oiG3Oir1D3WrqecFMo+AdZzJBDvK7eftxo38ga8kySuwLtQMS3YWD0EGnDXx4yeGKo+9hgNlpde6ZOFtUmKauyHwcbCDaiCfZ+Djp9ZjTjP7XZqbiSNCfL2fI64XOjivxoRBAQ2EvSxPK6BUVwcyOohosOXcagX1ErZugvwTBL5HVOeCoYLAXgnQQGDH4Of92qrv1mVL9TO6k2Ni1RfY7UdKC5vNBih1vX4xECgRAT65HZ8OdWpivSTLMPRdU2wxYI845Ajk3MOWz0BLcYopCJ3J/fG9BPzpZmCPvuSaa2y+DIIFf6YledOJZiFxZg2XU3JbrynhWNatRHYw4i6uPcybuGvi9R0v9cPyBdtGyJhaKdvo43WIAt4peWI/yxRQqFCCxyQK8issES5rR4pEVB/Aq8rShZT371ouftN1daw5nzh4NrXkr48OJqTyn5KzsKcjdfZ27LL5JLazpSSD6Jfzm/WwLDlnRkJ6PU+iKHrlozZA1JYDj6j0bB2IJ6M6EjXTE5Cx7vFnO7UkzRwPwHRpiWnuRWyghm2MgRtv+meaxJ3QxcmNxsvBag0c7ns1FduIH5NoBrfHNZER5qNKNmCEBIyqSZpixLNDKcJYdja2zZpPJY+Y3KIb2bs6d69a9PQJvhhZc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
