travis:
  secure:
    BINSTAR_TOKEN: UHc73TLH37HxW2Z7gntTCEK6rUUq2oggxu0Ok1dydYTuJn3scmPDVSs2VtuAogyE3IrDnnZLSBcDLO5KrFVYTBwfvHgMV/XfIxkaE7dnqiMCFQBc3+BuHOCnRERbv9WJeSCoaJO6p4PNx74wgI6n8GQuZGu1u4ExJRGarJCeNP6leP/6Z2TvVPGgABoCllp7kLNmTfoENIalbu+JPzW9AHYrpM/kvexAKxZjuDY1aOOONT4y+gbeXRK+W8spvjolQT7LkFFJK8u22JcHWx56E5tOczIW1j2ZyAhubePr59mfaSayc4poBCzA1QGgr2cBY+2ZR8yJ4fvt1koQcjVaI9lAEseAahpQpo75kwFKHa4Ao41qgoCRTaRuKUWo2zMlwTHC1/aKWH7IDagxzPEybtAfvazrO2kZ8X1s9mVFTFV/Yasks7wJxAKJlkXSDP1uA1Ko0M4jbvevz8qO6C6u7YZp08yqzt+9IDDfwVVApUZAyRVbzP8jULaAg1HMjGrGDzRAP0H60ESFumxdCnpJehUo/QbeZ2TwjNw+gXghrAiK5tsojt9KATvogUXqshrSw2u+7giRYn0HVhkypb9wvk7FravEUSUiyv9d3DDtQA3Vna6Ulp7lxtSSg1cLtqYC6C9e0I9jzgKZh9xy9tp7fnbs4qXL5H995rGpTSgE5v0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
