travis:
  secure:
    BINSTAR_TOKEN: muXw9EIBf4bdM6wONdVokqMnzqtszmvaOaS7Xj+q3aFRLfcugmILh97mTRvSmTXjr/GwxzxkWrMnghRWmgZIaTempljbZ4GDO8kZhe3kQgn4hMHpCH3jjuCVF7AhX6z1MHo0iuKtW9nbGYwrJ+lhbDWEEP8E8HsMo/ZfFaVVf7lPZgQXllN9j0Tvygc9GFaRNfffgCGvnJpVdL2SNFAEhKM4FgLv5gKHPBngAbiW3tGZwLIZNC4pvGPT+OxdFNWhE75hCCb/JSVQScB2Q/ZK0NWhkwoqX6Vb12iDpMYrE326ecgEfKCxnkAYeZy8q/A7v3mIej6cR/B+zLPEPwCYlhw0Amqqibpisa1u4ELnV+QB93jdRb2PQKoYB/sITW9osnXwV/qxtVVm+X4nsA7ok8Vk2AxzFyC0CaeVhRnJmoU1ycwIAFzir2ZP2erqz7IEaDH8yBWnbW45eXbi/zwWx2530tN7wyOjXGGNX8gHP/khrev1zQGAPutihvKvgB0ojwQz5zOxBD1AV/6Pwgz+5Y/pAy6d7zXiX0lSY98+VEkYka0fd+YSpHP1fW6O1wV92fuAbjltfmRrgu+Vi6/qQeLnZjYGZP3U5jAwfAI8vXfJetxX8L+ggY/Msfgxv2ZoObDf9hbMukVHktD+/3Ib2Z9jKlbXvwmQxZscGfu62C4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
