travis:
  secure:
    BINSTAR_TOKEN: QaOi94szZl6e5+Ha+F4XRCz1RDDql59NWWqA+0zZL0LDsV1NIP3EJbZ1yTRvafW0lhpFq0H1qRkXZdWLKsMab7GBNndj+u5hsGPUGK+t31FEB9OMjnOed+pSZZehqHxZtg1MG8vbwn5Sjitov9mda5YwMIhILVsunjkSISY7caesyHqkmV400mBljgcA7S4ATy1SeVJjX3sXOgMeQ0IcGyhYNiCM2w5aciYrLcIwzTD4oIm3G6F2yEgk9y7IPr0YVXJHLFwqF6GN2F2Bbnmme8PK4f9/92gY65pFYg32VFZg235IU3sUFolkvq5HILQcbmK2Sx/LNqBGHGzn4+1Pc7lm0iWJG55iRXhkMqXJgr612SNtcjI9h3l4cKxWOE/P0X/Y9lNGH6YTSS12EmGxGw2RR8JSF5z7xnqc5Csi4XiBKf//dxpDVZTKFfMVZx/KcvmTb0ucAdP226yM8Ahzm5O+GGDlHG70d+5ztJaSqsfSPkwSF1TmekZs7IFR/4vuyWFmu1D8RVvCA/w9tVEtIXjzx3GvCcWMLi7w1ojsjfqm8OB2lqxu+kq9ocuWzSCqhx4Q3U9cXNQcMm9dIFmFKXaCGkE8Sx3GRZeDWqJUBCO6jggjzbpXB4ETlyApOawS3728oPma7llNaSUKl8HoaNTbjqSbHfevn6lCl/IBLwk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
